
import java.util.*;
public class ProjSol {

	public static void main(String[] args) {
		// TODO Auto-generated method stub


		/*
		 * Problem 2: Each new term in the Fibonacci sequence is generated by adding the 
		 * previous two terms. By starting with 1 and 2 the first 10 terms will be:
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
		 * 
		 * By considering the terms in the fibonacci sequence whose values do not 
		 * excede four million, find the sum of the even-valued terms.
		 * 
		 * Doing this for GitChall
		 */

		int sum = 0;
		int x = 0;
		int y = 1;
		int z = 0;
		int i = 0;
			
		while( z < 4000000){
			z = x + y;
			x = y;
			y = z;
			if((z%2) == 0) sum += z;
			i++;
		}
	
		
		System.out.println(sum);
	}
}

